application:
    name: pia-merchant-servce
    monitoring:
      host: hawkular.nets.eu
      port: 8081
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:AZ;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    password: null
    username: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddlAuto: validate
      namingStrategy: org.hibernate.cfg.EJB3NamingStrategy
    show-sql: false
flyway:
  locations: classpath:dbscripts/h2
logging:
    level:
      ROOT: INFO
      com.sun.xml.internal.ws: TRACE
      serviceLogger: DEBUG
management:
  context-path: /management
  port: 8081
  security:
    enabled: false
secrets:
    path: ./etc/secrets
netaxept:
    force3Dsecure: false
    terminalPaymentMethods: Visa,MasterCard
    connection:
        timeout: 2000
        
